### ISSUE TITLE
feat - Компоненты Адмирал

### ISSUE THREAD

**Issue by syros** [AdmiralDS/website#53]
![image](https://github.com/AdmiralDS/website/assets/1932140/44b9eae2-9c45-47f5-80f5-59416de81de6)

- [x] Добавить еще 2 компонента (пока не определены)
- [x] Кнопки-переключатели при переполнении должны уходить в многоточие и иметь 1 строку

**Comment by Vandervovk** [comment]
Давайте возьмем еще тоаст
![image](https://github.com/AdmiralDS/website/assets/148227683/4ae6e7cb-5ae4-49f1-9f3a-f5da4066839a)
и дропдаун с иконками 
![image](https://github.com/AdmiralDS/website/assets/148227683/7c2d49ec-2fd4-4db6-9947-a265914e7cb5)
