### ISSUE TITLE
Поправить градиент на диагональ в баннерах и фонах

### ISSUE THREAD

**Issue by Vandervovk** [AdmiralDS/website#60]
![image](https://github.com/AdmiralDS/website/assets/148227683/12d4536b-3f93-4066-92d8-e4f1b8aba927)

![image](https://github.com/AdmiralDS/website/assets/148227683/4ea267ae-d029-4783-8330-6eef6b481585)

**Comment by Parasjona** [comment]
@Vandervovk Необходимо обсудить детали по точным параметрам градиентов, требуется встреча
